# Generated by Django 5.1.2 on 2024-11-07 05:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_date_event_location'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-created_at'], 'verbose_name': 'Ticket', 'verbose_name_plural': 'Tickets'},
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='purchase_date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='buyer',
        ),
        migrations.AddField(
            model_name='ticket',
            name='amount',
            field=models.PositiveIntegerField(default=0, help_text='Amount of the ticket in the smallest currency unit (e.g., cents).', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='ticket',
            name='description',
            field=models.TextField(default='', help_text='A description of the ticket.', max_length=1000),
        ),
        migrations.AddField(
            model_name='ticket',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image associated with the ticket.', null=True, upload_to='tickets/images/'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Number of tickets available for this type.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('VIP', 'VIP'), ('Standard', 'Standard'), ('Economy', 'Economy')], default='Standard', help_text='Type of the ticket (e.g., VIP, Standard, Economy).', max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='event',
            field=models.ForeignKey(help_text='The event to which this ticket is linked.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='events.event'),
        ),
    ]
